/**
 * @minecraft-api/schemas
 *
 * Zod schemas for Minecraft API with OpenAPI metadata
 */

// Re-export zod for convenience
export { z } from "@hono/zod-openapi"
// Biome schemas
export {
  type Biome,
  type BiomeCategory,
  BiomeCategorySchema,
  type BiomeEffects,
  BiomeEffectsSchema,
  type BiomeListResponse,
  BiomeListResponseSchema,
  type BiomePathParams,
  BiomePathParamsSchema,
  type BiomeQuery,
  BiomeQuerySchema,
  BiomeSchema,
  type BiomeSpawnEntry,
  BiomeSpawnEntrySchema,
  type BiomeSpawnSettings,
  BiomeSpawnSettingsSchema,
  type Carver,
  CarverSchema,
  type FeaturePlacement,
  FeaturePlacementSchema,
  type PrecipitationType,
  PrecipitationTypeSchema,
} from "./biomes.js"
// Block schemas
export {
  type Block,
  type BlockDrop,
  BlockDropSchema,
  type BlockListResponse,
  BlockListResponseSchema,
  type BlockMaterial,
  BlockMaterialSchema,
  type BlockPathParams,
  BlockPathParamsSchema,
  type BlockQuery,
  BlockQuerySchema,
  BlockSchema,
  type BlockSoundType,
  BlockSoundTypeSchema,
  type BlockStateProperty,
  BlockStatePropertySchema,
  type BlockStatePropertyType,
  BlockStatePropertyTypeSchema,
  type BoundingBox,
  BoundingBoxSchema,
  type HarvestTool,
  HarvestToolSchema,
} from "./blocks.js"
// Common schemas
export {
  type BedrockChange,
  BedrockChangeSchema,
  type BedrockMeta,
  BedrockMetaSchema,
  type Edition,
  EditionSchema,
  type EditionVersionQuery,
  EditionVersionQuerySchema,
  type ErrorResponse,
  ErrorSchema,
  type LocaleQuery,
  LocaleQuerySchema,
  type LocalizedText,
  LocalizedTextSchema,
  type NamespacedId,
  NamespacedIdSchema,
  type PaginationMeta,
  PaginationMetaSchema,
  type PaginationQuery,
  PaginationQuerySchema,
  type SearchQuery,
  SearchQuerySchema,
} from "./common.js"
// Effect and potion schemas
export {
  type AttributeModifierOperation,
  AttributeModifierOperationSchema,
  type Effect,
  type EffectAttributeModifier,
  EffectAttributeModifierSchema,
  type EffectCategory,
  EffectCategorySchema,
  type EffectListResponse,
  EffectListResponseSchema,
  type EffectPathParams,
  EffectPathParamsSchema,
  type EffectQuery,
  EffectQuerySchema,
  EffectSchema,
  type Potion,
  type PotionEffectInstance,
  PotionEffectInstanceSchema,
  type PotionListResponse,
  PotionListResponseSchema,
  type PotionPathParams,
  PotionPathParamsSchema,
  type PotionQuery,
  PotionQuerySchema,
  PotionSchema,
  type PotionType,
  PotionTypeSchema,
} from "./effects.js"
// Enchantment schemas
export {
  type Enchantment,
  type EnchantmentCategory,
  EnchantmentCategorySchema,
  type EnchantmentCost,
  EnchantmentCostSchema,
  type EnchantmentEffect,
  EnchantmentEffectSchema,
  type EnchantmentListResponse,
  EnchantmentListResponseSchema,
  type EnchantmentPathParams,
  EnchantmentPathParamsSchema,
  type EnchantmentQuery,
  EnchantmentQuerySchema,
  EnchantmentSchema,
  type EnchantmentTarget,
  EnchantmentTargetSchema,
} from "./enchantments.js"

// Entity schemas
export {
  type Entity,
  type EntityAttribute,
  EntityAttributeSchema,
  type EntityCategory,
  EntityCategorySchema,
  type EntityClassification,
  EntityClassificationSchema,
  type EntityDimensions,
  EntityDimensionsSchema,
  type EntityExperience,
  EntityExperienceSchema,
  type EntityListResponse,
  EntityListResponseSchema,
  type EntityPathParams,
  EntityPathParamsSchema,
  type EntityQuery,
  EntityQuerySchema,
  EntitySchema,
  type LootEntry,
  LootEntrySchema,
  type SpawnCondition,
  SpawnConditionSchema,
} from "./entities.js"
// Item schemas
export {
  type ArmorProperties,
  ArmorPropertiesSchema,
  type EquipmentSlot,
  EquipmentSlotSchema,
  type FoodProperties,
  FoodPropertiesSchema,
  type FuelProperties,
  FuelPropertiesSchema,
  type Item,
  type ItemCategory,
  ItemCategorySchema,
  type ItemListResponse,
  ItemListResponseSchema,
  type ItemPathParams,
  ItemPathParamsSchema,
  type ItemQuery,
  ItemQuerySchema,
  type ItemRarity,
  ItemRaritySchema,
  ItemSchema,
  type ToolProperties,
  ToolPropertiesSchema,
} from "./items.js"
// Recipe schemas
export {
  type BlastingRecipe,
  BlastingRecipeSchema,
  type CampfireCookingRecipe,
  CampfireCookingRecipeSchema,
  type Recipe,
  type RecipeIngredient,
  RecipeIngredientSchema,
  type RecipeListResponse,
  RecipeListResponseSchema,
  type RecipePathParams,
  RecipePathParamsSchema,
  type RecipeQuery,
  RecipeQuerySchema,
  type RecipeResult,
  RecipeResultSchema,
  RecipeSchema,
  type RecipeType,
  RecipeTypeSchema,
  type ShapedRecipe,
  ShapedRecipeSchema,
  type ShapelessRecipe,
  ShapelessRecipeSchema,
  type SmeltingRecipe,
  SmeltingRecipeSchema,
  type SmithingTransformRecipe,
  SmithingTransformRecipeSchema,
  type SmithingTrimRecipe,
  SmithingTrimRecipeSchema,
  type SmokingRecipe,
  SmokingRecipeSchema,
  type StonecuttingRecipe,
  StonecuttingRecipeSchema,
} from "./recipes.js"
// Version schemas
export {
  type BedrockPlatform,
  BedrockPlatformSchema,
  type BedrockVersion,
  BedrockVersionSchema,
  type JavaVersion,
  JavaVersionSchema,
  type JavaVersionType,
  JavaVersionTypeSchema,
  type Version,
  type VersionListResponse,
  VersionListResponseSchema,
  type VersionPathParams,
  VersionPathParamsSchema,
  type VersionQuery,
  VersionQuerySchema,
  VersionSchema,
} from "./versions.js"
