name = "minecraft-api"
main = "src/index.ts"
compatibility_date = "2025-01-03"

# compatibility_flags = [ "nodejs_compat" ]

routes = [{ pattern = "minecraft.api.geak.dev", custom_domain = true }]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
