name = "minecraft-api"
main = "src/index.ts"
compatibility_date = "2025-01-03"

routes = [{ pattern = "api.minecraft.geak.dev", custom_domain = true }]

[[r2_buckets]]
binding = "R2"
bucket_name = "minecraft-assets"
preview_bucket_name = "minecraft-assets"

[observability]
enabled = true
